### ISSUE TITLE
Remove deprecated modules/classes in 5.0.0 release

### ISSUE THREAD

**Issue by rahulporuri** [enthought/chaco#580]
- [x] [`variable_size_scatterplot`](https://github.com/enthought/chaco/blob/c758a65222a2caef9a3d2c074ae9dd5775a3a77e/chaco/variable_size_scatterplot.py) (#691)
- [x] [`drag_tool`](https://github.com/enthought/chaco/blob/c758a65222a2caef9a3d2c074ae9dd5775a3a77e/chaco/tools/drag_tool.py) (#670)
- [x] [`chaco.chaco_plot_container_editor`](https://github.com/enthought/chaco/blob/c758a65222a2caef9a3d2c074ae9dd5775a3a77e/chaco/chaco_plot_container_editor.py) (#670)
- [x] [`chaco.color_mapper.ColorMapper._map`](https://github.com/enthought/chaco/blob/ad3c77eebee935631f472f1f8ee52d77b5cf71a9/chaco/color_mapper.py#L393-L429)
- [x] [`bg_color` property on `chaco.chaco_plot_editor.ChacoPlotItem`](https://github.com/enthought/chaco/blob/ad3c77eebee935631f472f1f8ee52d77b5cf71a9/chaco/chaco_plot_editor.py#L108-L109) (#688)
- [x] [deprecated traits on `chaco.base_plot_container.BasePlotContainer`](https://github.com/enthought/chaco/blob/ad3c77eebee935631f472f1f8ee52d77b5cf71a9/chaco/base_plot_container.py#L41-L60) (#670)

Plot Frames
-------------
- [x] [`chaco.base_plot_frame`](https://github.com/enthought/chaco/blob/ad3c77eebee935631f472f1f8ee52d77b5cf71a9/chaco/base_plot_frame.py) (#692)
- [x] [`chaco.simple_plot_frame`](https://github.com/enthought/chaco/blob/ad3c77eebee935631f472f1f8ee52d77b5cf71a9/chaco/simple_plot_frame.py) (#692)
- [x] [`chaco.cross_plot_frame`](https://github.com/enthought/chaco/blob/ad3c77eebee935631f472f1f8ee52d77b5cf71a9/chaco/cross_plot_frame.py) (#692)

Zoom Classes
---------------
- [x] [`chaco.tools.simple_zoom`](https://github.com/enthought/chaco/blob/ad3c77eebee935631f472f1f8ee52d77b5cf71a9/chaco/tools/simple_zoom.py) (#670)
- [x] [traits and methods in `chaco.tools.better_selecting_zoom.BetterSelectingZoom`](https://github.com/enthought/chaco/blob/ad3c77eebee935631f472f1f8ee52d77b5cf71a9/chaco/tools/better_selecting_zoom.py) (#670)
- [x] [`chaco.tools.base_zoom_tool`](https://github.com/enthought/chaco/blob/ad3c77eebee935631f472f1f8ee52d77b5cf71a9/chaco/tools/base_zoom_tool.py) (#670)

**Comment by rahulporuri** [comment]
@corranwebster @jvkersch do you have comments about these deprecations?

**Comment by rahulporuri** [comment]
https://github.com/enthought/chaco/blob/f7cdff7bac428852b343f5311fb397c08a19c789/chaco/scatter_markers.py is not officially deprecated but it looks redundant and can possibly be removed.

**Comment by corranwebster** [comment]
> https://github.com/enthought/chaco/blob/f7cdff7bac428852b343f5311fb397c08a19c789/chaco/scatter_markers.py is not officially deprecated but it looks redundant and can possibly be removed.

Yes, this can be removed.

**Comment by aaronayres35** [comment]
closing this as the last item from the PR description has been resolved now that #691 has just been merged
